modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}
Minimalist, informative design with theme, scale, and layout options.
'''
logoFile = "logo.png"

[[dependencies.createanalyzerlite]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.createanalyzerlite]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.createanalyzerlite]]
modId = "create"
type = "optional"
versionRange = "[0.5.1,)"
ordering = "NONE"
side = "CLIENT"