modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"
issueTrackerURL = "https://github.com/d1ts05/CreateAnalyzerLite/issues"

[[mods]]
modId="createanalyzerlite"
version="0.3.3"
displayName="Create Analyzer Lite"
authors="Zivalez"
description = '''
Client-only HUD for Create metrics (RPM, stress, nodes) with in-game config. Minimalist overlay with theme/scale/layout options.

Features:
• Real-time RPM, stress, and network metrics
• Compact & Expanded display modes
• Theme system (Light/Dark/Auto)
• Performance optimized with caching
• Works gracefully without Create mod
'''
displayURL="https://github.com/d1ts05/CreateAnalyzerLite"

[[dependencies.createanalyzerlite]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.createanalyzerlite]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.createanalyzerlite]]
modId = "create"
type = "optional"
versionRange = "[0.5.1,)"
ordering = "NONE"
side = "CLIENT"