modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"
issueTrackerURL = "https://github.com/d1ts05/CreateAnalyzerLite/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_description}

Features:
• Real-time RPM, stress, and network metrics
• Compact & Expanded display modes
• Theme system (Light/Dark/Auto)
• Performance optimized with caching
• Works gracefully without Create mod
'''

[[dependencies.createanalyzerlite]]
modId = "neoforge"
type = "required"
versionRange = "[21.0.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.createanalyzerlite]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.createanalyzerlite]]
modId = "create"
type = "optional"
versionRange = "[0.5.1,)"
ordering = "NONE"
side = "CLIENT"